# workflof adı 
name: Terraform Plan & Drift Detection

# Wworkflowu tetikleyecek olaylar 
on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalış test kontrol
  workflow_dispatch:      # Github ui üzerinden manuel tetikleme izni
  pull_request:          # Pull Request açıldığında ve güncelledniğnde çalışacak olan 
    branches: [ main ]   # Sadece main branch'e açılan PR'larda çalışır

# Workflow'da çalışacak jobslar ve tanımı
jobs:
  terraform:             # Job adı: terraform
    runs-on: ubuntu-latest    # İş akışının çalışacağı ortam: Ubuntu'nun en son sürümü
    
    steps:              # İş akışındaki adımlar
    # Repo'yu GitHub runner'a klonlar
    - uses: actions/checkout@v2
    
    # Terraform'u runner'a kurar ve yapılandırır
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'  # Kullanılacak Terraform sürümü
        
    # Azure'a authentication yapar
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}  # GitHub Secrets'dan Azure kimlik bilgilerini alır
        
    # Terraform çalışma dizinini başlatır
    - name: Terraform Init
      run: |
        cd vnet
        terraform init
        
    # Terraform plan çalıştırır ve olası değişiklikleri tespit eder
    - name: Terraform Plan
      id: plan           # Bu adıma referans vermek için kullanılacak ID
      run: |
        cd vnet
        terraform plan -out=plan.tfplan
      continue-on-error: true  # Hata olsa bile workflow'u durdurmaz
        
    # Drift tespit edilirse GitHub Issue oluşturur
    - name: Create Issue on Drift
      if: steps.plan.outcome == 'failure' || steps.plan.outputs.stdout != ''  # Plan başarısız olursa veya değişiklik varsa
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Infrastructure Drift Detected',
            body: 'Terraform plan has detected infrastructure drift. Please review the changes.',
            labels: ['drift-detected', 'infrastructure']
          })
